swagger: '2.0'
info:
  description: Accounts service for eDropin
  version: 1.0.0
  title: eDropin Accounts
  license:
    name: UNLICENSED
  contact:
    name: Saj Arora
    email: dev@edropin.com
host: 'accounts-dot-edropin-playground.appspot.com'
basePath: /v1
tags:
  - name: eaAccounts
    description: User accounts on eDropin
  - name: eaProfiles
    description: Profiles such as course providers and businesses
schemes:
  - https
produces:
  - application/json
securityDefinitions:
  Authorization:
    type: apiKey
    in: header
    name: Authorization
  ClientKey:
    type: apiKey
    in: header
    name: X-Client-Key
security:
  - ClientKey: []
    Authorization: []
paths:
  ### Accounts
  /accounts:
    get:
      tags:
        - eaAccounts
      summary: Get Account
      operationId: getAccount
      responses:
        '200':
          description: Account
          schema:
            $ref: '#/definitions/EaAccount'
        '401':
          $ref: '#/responses/UnauthorizedError'
        '405':
          $ref: '#/responses/InvalidInputResponse'
        '500':
          $ref: '#/responses/Default500ErrorResponse'
    put:
      tags:
        - eaAccounts
      summary: Create/update existing account
      operationId: updateAccount
      parameters:
        - in: body
          name: accountProps
          description: Account object that needs to be updated
          required: true
          schema:
            $ref: '#/definitions/EaAccountUpdate'
      responses:
        '200':
          description: Account updated
          schema:
            $ref: '#/definitions/EaAccount'
        '400':
          description: Invalid ID supplied
        '401':
          $ref: '#/responses/UnauthorizedError'
        '405':
          $ref: '#/responses/InvalidInputResponse'
        '500':
          $ref: '#/responses/Default500ErrorResponse'
  ### End of Accounts
  
  ### Profiles
  '/profiles':
    get:
      tags:
        - eaProfiles
      summary: Get Profiles
      operationId: getAllProfiles
      parameters:
        - in: query
          name: profileType
          type: string
        - $ref: '#/parameters/cursor'
        - $ref: '#/parameters/limit'
      responses:
        '200':
          description: Profile
          schema:
            $ref: '#/definitions/EaPagedProfile'
        '401':
          $ref: '#/responses/UnauthorizedError'
        '405':
          $ref: '#/responses/InvalidInputResponse'
        '500':
          $ref: '#/responses/Default500ErrorResponse'
    post:
      tags:
        - eaProfiles
      summary: Create profile
      operationId: createProfile
      parameters:
        - in: body
          name: profileProps
          description: Profile object that needs to be created
          required: true
          schema:
            $ref: '#/definitions/EaProfileUpdate'
      responses:
        '200':
          description: Profile created
          schema:
            $ref: '#/definitions/EaProfile'
        '400':
          description: Invalid ID supplied
        '401':
          $ref: '#/responses/UnauthorizedError'
        '405':
          $ref: '#/responses/InvalidInputResponse'
        '500':
          $ref: '#/responses/Default500ErrorResponse'
  '/profiles/get-multi':
    get:
      tags:
        - eaProfiles
      summary: Get Multiple Profiles
      operationId: getMultipleProfiles
      parameters:
        - in: query
          name: profileIds
          type: array
          items:
            type: string
      responses:
        '200':
          description: Profile
          schema:
            $ref: '#/definitions/EaPagedProfile'
        '401':
          $ref: '#/responses/UnauthorizedError'
        '405':
          $ref: '#/responses/InvalidInputResponse'
        '500':
          $ref: '#/responses/Default500ErrorResponse'
  '/profiles/{profileId}':
    parameters:
      - $ref: '#/parameters/profileId'
    get:
      tags:
        - eaProfiles
      summary: Get a profile from the directory
      operationId: getProfile
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/EaProfile'
        '400':
          description: Invalid ID supplied
        '404':
          description: Profile not found
        '500':
          $ref: '#/responses/Default500ErrorResponse'
    put:
      tags:
        - eaProfiles
      summary: Update an existing profile
      operationId: updateProfile
      parameters:
        - in: body
          name: profileProps
          description: Profile object that needs to be updated
          required: true
          schema:
            $ref: '#/definitions/EaProfile'
      responses:
        '200':
          description: Profile updated
          schema:
            $ref: '#/definitions/EaProfile'
        '400':
          description: Invalid ID supplied
        '401':
          $ref: '#/responses/UnauthorizedError'
        '404':
          description: Profile not found
        '405':
          $ref: '#/responses/InvalidInputResponse'
        '500':
          $ref: '#/responses/Default500ErrorResponse'
    delete:
      tags:
        - eaProfiles
      summary: Delete an existing profile
      operationId: deleteProfile
      responses:
        '204':
          description: Profile deleted
        '400':
          description: Invalid ID supplied
        '401':
          $ref: '#/responses/UnauthorizedError'
        '404':
          description: Profile not found
        '500':
          $ref: '#/responses/Default500ErrorResponse'
  '/profiles/{profileId}/permissions/{accountId}':
    parameters:
      - $ref: '#/parameters/profileId'
      - $ref: '#/parameters/accountId'
    get:
      tags:
        - eaProfiles
      summary: Get permission for account
      operationId: getAccountPermissionForProfile
      responses:
        '200':
          description: Permissions for account
          schema:
            $ref: "#/definitions/EaPermission"
        '401':
          $ref: '#/responses/UnauthorizedError'
        '405':
          $ref: '#/responses/InvalidInputResponse'
        '500':
          $ref: '#/responses/Default500ErrorResponse'
    put:
      tags:
        - eaProfiles
      summary: Set permission for profile
      operationId: setProfilePermission
      parameters:
        - in: body
          name: permissionProps
          description: Permissions
          required: true
          schema:
            $ref: '#/definitions/EaPermissionInput'
      responses:
        '200':
          description: Permission set
          schema:
            $ref: '#/definitions/EaPermission'
        '401':
          $ref: '#/responses/UnauthorizedError'
        '405':
          $ref: '#/responses/InvalidInputResponse'
        '500':
          $ref: '#/responses/Default500ErrorResponse'
  '/profiles/{profileId}/permissions/{accountId}/check':
    parameters:
      - $ref: '#/parameters/profileId'
      - $ref: '#/parameters/accountId'
    get:
      tags:
        - eaProfiles
      summary: Check account has permission
      operationId: checkAccountHasPermission
      parameters:
        - in: query
          type: string
          required: true
          name: permission
      responses:
        '200':
          description: Account has Permission
          schema:
            type: boolean
        '401':
          $ref: '#/responses/UnauthorizedError'
        '405':
          $ref: '#/responses/InvalidInputResponse'
        '500':
          $ref: '#/responses/Default500ErrorResponse'
  '/profiles/{profileId}/all-permissions':
    parameters:
      - $ref: '#/parameters/profileId'
    get:
      tags:
        - eaProfiles
      summary: List all profile permissions
      operationId: getProfilePermission
      parameters:
        - $ref: '#/parameters/cursor'
        - $ref: '#/parameters/limit'
      responses:
        '200':
          description: List of Users with permissions linked to this profile
          schema:
            $ref: '#/definitions/EaPagedPermission'
        '401':
          $ref: '#/responses/UnauthorizedError'
        '405':
          $ref: '#/responses/InvalidInputResponse'
        '500':
          $ref: '#/responses/Default500ErrorResponse'
  '/profiles/search':
    get:
      tags:
        - eaProfiles
      summary: Search Profiles
      operationId: searchProfile
      parameters:
        - in: query
          name: q
          type: string
        - in: query
          name: profileType
          type: string
      responses:
        '200':
          description: Profiles
          schema:
            $ref: '#/definitions/EaPagedProfile'
        '401':
          $ref: '#/responses/UnauthorizedError'
        '405':
          $ref: '#/responses/InvalidInputResponse'
        '500':
          $ref: '#/responses/Default500ErrorResponse'
  ### End of Courses

parameters:
  limit:
    name: limit
    in: query
    description: Number of items returned
    type: integer
    format: int32
    minimum: 0
    exclusiveMinimum: true
    maximum: 50
    exclusiveMaximum: false
    multipleOf: 10
    default: 20
  cursor:
    name: cursor
    in: query
    description: Start Cursor for query
    type: string
  accountId:
    name: accountId
    in: path
    description: Account Id
    type: string
    required: true
  profileId:
    name: profileId
    in: path
    description: Profile Id
    type: string
    required: true
responses:
  Default500ErrorResponse:
    description: An unexpected error occured.
    schema:
      $ref: '#/definitions/DefaultError'
  InvalidInputResponse:
    description: Validation exception
  UnauthorizedError:
    description: API key is missing or invalid
    headers:
      WWW_Authenticate:
        type: string
definitions:
  # Extendable Models
  EaBaseId:
    type: object
    properties:
      id:
        type: string
      created:
        type: integer
        format: int32
        readOnly: true
      modified:
        type: integer
        format: int32
        readOnly: true
      version:
        type: string
        readOnly: true
  
  EaCreator:
    type: object
    allOf:
      - $ref: '#/definitions/EaBaseId'
      - properties:
          creatorId:
            type: string
            
  EaPagination:
    type: object
    properties:
      pageSize:
        type: integer
        format: int32
      nextCursor:
        type: string
      total:
        type: integer
        format: int32
  ### End Extendable Models
  
  ### Components
  EaAddress:
    type: object
    properties:
      line1:
        type: string
      line2:
        type: string
      line3:
        type: string
      city:
        type: string
      stateCode:
        type: string
      state:
        type: string
      country:
        type: string
      zip:
        type: string
      geoloc:
        $ref: '#/definitions/EaGeoloc'
  
  EaGeoloc:
    type: object
    properties:
      lat:
        type: number
        format: float
      lng:
        type: number
        format: float
  
  DefaultError:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
  
  ### Permissions
  EaPermission:
    type: object
    properties:
      id:
        type: string
      creatorId:
        type: string
      entityKind:
        type: string
      entityId:
        type: string
      permissions:
        type: object
  EaPermissionInput:
    type: object
    properties:
      permissions:
        type: object
  EaPagedPermission:
    type: object
    properties:
      pageData:
        $ref: '#/definitions/EaPagination'
      allPermission:
        type: array
        items:
          type: string
      items:
        type: array
        items:
          $ref: '#/definitions/EaPermission'
  ### End Permissions
  
  ### Account
  EaAccountUpdate:
    type: object
    properties:
      name:
        type: string
      picture:
        type: string
      website:
        type: string
      bio:
        type: string
      shortBio:
        type: string
  EaAccount:
    type: object
    allOf:
      - $ref: '#/definitions/EaBaseId'
      - $ref: '#/definitions/EaAccountUpdate'
  ### End Account
  
  ### Profile
  EaProfileBase:
    type: object
    properties:
      name:
        type: string
      profileType:
        type: string
      picture:
        type: string
      videoLink:
        type: string
      pictures:
        type: string
      bio:
        type: string
      shortBio: 
        type: string
      location:
        type: string
      address:
        $ref: '#/definitions/EaAddress'
      website:
        type: string
      facebook:
        type: string
      linkedIn: 
        type: string
      instagram:
        type: string
  EaProfileUpdate:
    type: object
    allOf:
      - $ref: '#/definitions/EaProfileBase'
  EaProfile:
    type: object
    allOf:
      - $ref: '#/definitions/EaCreator'
      - $ref: '#/definitions/EaProfileBase'
  EaProfileSummary:
    type: object
    properties:
      id:
        type: string
      name: 
        type: string
      picture:
        type: string
      shortBio:
        type: string
      location:
        type: string
  EaPagedProfile:
    type: object
    properties:
      pageData:
        $ref: '#/definitions/EaPagination'
      items:
        type: array
        items:
          $ref: '#/definitions/EaProfileSummary'