swagger: '2.0'
info:
  contact:
    email: dev@edropin.com
    name: Saj Arora
  description: Events Internal service for eDropin
  license:
    name: UNLICENSED
  title: eDropin Events Internal
  version: 1.0.0
host: localhost:9003
basePath: /
schemes:
  - http
paths:

  ### CRON JOBS
  '/cron/delete':
    get:
      security: 
        - CronKey: []
      produces:
        - application/json
      responses:
        '200':
          description: Cron Job Run Result
          schema:
            $ref: '#/definitions/EeSuccess'
      tags:
        - eeCron
      operationId: executeDeletionCron
      summary: Delete all event resources marked with isDeleted flag and take all necessary actions to clean up related resources
  '/cron/event-messages':
    get:
      security: 
        - CronKey: []
      produces:
        - application/json
      responses:
        '200':
          description: Cron Job Run Result
          schema:
            $ref: '#/definitions/EeSuccess'
      tags:
        - eeCron
      operationId: queueNewMessages
      summary: Queue deferred event messages that are within the window of task execution max delay
  
  ### PUBSUB
  '/pubsub/update-event-ticket':
    post:
      security:
        - PubsubKey: []
      produces:
        - application/json
      parameters:
        - description: Pubsub data
          in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/EePubsubInput'
      responses:
        '200':
          description: Pubsub result
          schema:
            $ref: '#/definitions/EeSuccess'
      tags:
        - eePubsub
      operationId: updateEventTicket
      summary: Update event ticket, subscription for store item add, update and delete
  
  '/pubsub/process-ticket-sale':
    post:
      security:
        - PubsubKey: []
      produces:
        - application/json
      parameters:
        - description: Pubsub data
          in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/EePubsubInput'
      responses:
        '200':
          description: Pubsub result
          schema:
            $ref: '#/definitions/EeSuccess'
      tags:
        - eePubsub
      operationId: processTicketSale
      summary: process ticket sale data to create attendees
  
  '/pubsub/process-dropin-complete':
    post:
      security:
        - PubsubKey: []
      produces:
        - application/json
      parameters:
        - description: Pubsub data
          in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/EePubsubInput'
      responses:
        '200':
          description: Pubsub result
          schema:
            $ref: '#/definitions/EeSuccess'
      tags:
        - eePubsub
      operationId: processDropinComplete
      summary: process automations linked to this dropin completion
  
definitions:
  EeSuccess:
    properties:
      message:
        type: object
      success:
        type: boolean
    type: object
    
  EePubsubInput:
    type: object
    properties:
      subscription:
        type: string
      data:
        type: string
      messageId:
        type: string
  
securityDefinitions:
  ServiceKey:
    in: header
    name: X-Service-Key
    description: Client Key
    type: apiKey
  PubsubKey:
    in: query
    name: apiKey
    description: Pubsub Key
    type: apiKey
  CronKey:
    in: query
    name: apiKey
    description: Cron Key
    type: apiKey
security:
  - ServiceKey: []
tags:
  - description: Handle all subscription callbacks
    name: eePubsub
  - description: Handle all cron jobs
    name: eeCron

