swagger: '2.0'
info:
  contact:
    email: dev@edropin.com
    name: Saj Arora
  description: Events Internal service for eDropin
  license:
    name: UNLICENSED
  title: eDropin Events Internal
  version: 1.0.0
host: localhost:9003
basePath: /
schemes:
  - http
paths:

  ### CRON JOBS
  '/cron/delete':
    get:
      security: 
        - CronKey: []
      produces:
        - application/json
      responses:
        '200':
          description: Cron Job Run Result
          schema:
            $ref: '#/definitions/EeSuccess'
      tags:
        - eeCron
      operationId: executeDeletionCron
      summary: Delete all event resources marked with isDeleted flag and take all necessary actions to clean up related resources
  '/cron/queue-messages':
    get:
      security: 
        - CronKey: []
      produces:
        - application/json
      responses:
        '200':
          description: Cron Job Run Result
          schema:
            $ref: '#/definitions/EeSuccess'
      tags:
        - eeCron
      operationId: queueMessages
      summary: Queue deferred event messages that are within the window of task execution max delay
  
  ### PUBSUB
  '/pubsub/update-event-ticket':
    post:
      security:
        - PubsubKey: []
      produces:
        - application/json
      parameters:
        - description: Pubsub data
          in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/EePubsubInput'
      responses:
        '200':
          description: Pubsub result
          schema:
            $ref: '#/definitions/EeSuccess'
      tags:
        - eePubsub
      operationId: updateEventTicket
      summary: Update event ticket, subscription for store item add, update and delete
  
  '/pubsub/process-ticket-sale':
    post:
      security:
        - PubsubKey: []
      produces:
        - application/json
      parameters:
        - description: Pubsub data
          in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/EePubsubInput'
      responses:
        '200':
          description: Pubsub result
          schema:
            $ref: '#/definitions/EeSuccess'
      tags:
        - eePubsub
      operationId: processTicketSale
      summary: process ticket sale data to create attendees
  
  '/pubsub/process-dropin-complete':
    post:
      security:
        - PubsubKey: []
      produces:
        - application/json
      parameters:
        - description: Pubsub data
          in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/EePubsubInput'
      responses:
        '200':
          description: Pubsub result
          schema:
            $ref: '#/definitions/EeSuccess'
      tags:
        - eePubsub
      operationId: processDropinComplete
      summary: process automations linked to this dropin completion
      
  ### TASKS
  '/tasks/process-message':
    post:
      security:
        - TaskKey: []
      produces:
        - application/json
      parameters:
        - description: Message data
          in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/EePubsubInput'
      responses:
        '200':
          description: Task result
          schema:
            $ref: '#/definitions/EeSuccess'
      tags:
        - eeTasks
      operationId: processMessage
      summary: Process a message
  
  ### OPS
  '/ops/migration/{buildId}':
    post:
      security:
        - AdminKey: []
      produces:
        - application/json
      parameters:
        - in: path
          required: true
          type: string
          name: buildId
          description: Build ID - Used for selecting the right case for migration
        - description: Op data
          in: body
          name: body
          required: false
          schema:
            type: object
      responses:
        '200':
          description: Pubsub result
          schema:
            $ref: '#/definitions/EeSuccess'
      tags:
        - eeOps
      operationId: migrate
      summary: Migration endpoint
  
  '/ops/certificate-templates':
    post:
      security:
        - AdminKey: []
      produces:
        - application/json
      parameters:
        - in: body
          required: true
          name: body
          description: Certificate template object to edit/create
          schema:
            $ref: '#/definitions/EeEventCertificateTemplate'
      responses:
        '200':
          description: Pubsub result
          schema:
            $ref: '#/definitions/EeSuccess'
      tags:
        - eeOps
      operationId: upsertCertificateTemplate
      summary: Update/Create certificate templates
  '/ops/certificate-templates/{id}':
    delete:
      security:
        - AdminKey: []
      produces:
        - application/json
      parameters:
        - in: path
          required: true
          type: string
          name: id
          description: Certificate Template ID
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/EeSuccess'
      tags:
        - eeOps
      operationId: deleteCertificateTemplate
      summary: Delete a certificate template with the given ID
  
  
definitions:
  EeSuccess:
    properties:
      message:
        type: object
      success:
        type: boolean
    type: object
  
  EeBaseId:
    type: object
    properties:
      id:
        type: string
      createdOn:
        type: string
        readOnly: true
      modifiedOn:
        type: string
        readOnly: true
      version:
        type: string
        readOnly: true
      isDeleted:
        type: boolean
        default: false
      isDeactivated:
        type: boolean
        default: false
    
  EePubsubInput:
    type: object
    properties:
      subscription:
        type: string
      data:
        type: string
      messageId:
        type: string
  
  EeEventCertificateTemplate:
    allOf:
      - $ref: '#/definitions/EeBaseId'
      - required:
          - name
          - templateUrl
          - thumbnail
          - id
          - annotation
      - properties:
          name:
            type: string
          templateUrl:
            type: string
          annotation:
            type: object
          thumbnail:
            type: string
          isPace:
            type: boolean
          isCerp:
            type: boolean
  
securityDefinitions:
  TaskKey:
    in: query
    name: apiKey
    description: Task Key
    type: apiKey
  PubsubKey:
    in: query
    name: apiKey
    description: Pubsub Key
    type: apiKey
  CronKey:
    in: query
    name: apiKey
    description: Cron Key
    type: apiKey
  AdminKey:
    in: header
    name: X-Admin-Key
    description: Admin Key
    type: apiKey
tags:
  - description: Handle all subscription callbacks
    name: eePubsub
  - description: Handle all cron jobs
    name: eeCron
  - description: Handle all task callbacks
    name: eeTasks
  - description: Handle all ops (system admin only)
    name: eeOps

