swagger: '2.0'
info:
  contact:
    email: dev@edropin.com
    name: Saj Arora
  description: Store service for eDropin
  license:
    name: UNLICENSED
  title: eDropin Store Internal
  version: 1.0.11
host: localhost:9004
basePath: /
schemes:
  - http
paths:
  
  '/order-items/{orderItemId}/status':
    parameters:
      - $ref: '#/parameters/orderItemId'
    post:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - description: Refund body
          in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/EsOrderItem'
      responses:
        '200':
          description: Order Item
          schema:
            $ref: '#/definitions/EsOrderItem'
      tags:
        - esOrderItems
      operationId: createRefundRequest
      summary: Create a refund for an item
  
definitions:
  EsBaseId:
    properties:
      createdOn:
        readOnly: true
        type: string
      id:
        type: string
      modifiedOn:
        readOnly: true
        type: string
      creatorId:
        type: string
    type: object
  
  EsInstallmentPlanInput:
    type: object
    properties:
      interval:
        type: string
        enum:
          - week
          - month
          - year
      intervalCount:
        type: integer
        minimum: 1
        default: 1
      billingCycleAnchorTimestamp:
        type: integer
        minimum: 0
      payByTimestamp:
        type: integer
        minimum: 0
  EsInstallmentPlan:
    type: object
    allOf:
      - $ref: '#/definitions/EsInstallmentPlanInput'
      - properties:
          isInstallment:
            type: boolean
          amount:
            type: integer
            minimum: 0
          totalNumberOfPayments:
            type: integer
            minimum: 0
          deposit:
            type: integer
            minimum: 0
  
  EsOrderItem:
    type: object
    allOf:
      - $ref: '#/definitions/EsBaseId'
      - properties:
          ownerId:
            type: string
          merchantId:
            type: string
          merchantName:
            type: string
          merchantUsername:
            type: string
          itemType:
            type: string
          category:
            type: string
          categoryId:
            type: string
          storeItemId:
            type: string
          name:
            type: string
          shortName:
            type: string
          picture:
            type: string
          info:
            type: string
          link:
            type: string
          isRefundable:
            type: boolean
          refundAvailableUntil:
            type: integer
          refundPolicy:
            type: string
          requireCC:
            type: boolean
            default: true
          isCheckedOut:
            type: boolean
            default: false
          checkedOutWhen:
            type: integer
          isFailed:
            type: boolean
          failure:
            type: string
          appliedPromotions:
            type: array
            items:
              $ref: '#/definitions/EsOrderItemPromotion'
          itemQuantity:
            type: integer
            minimum: 0
            default: 0
          itemQuantityAvailable:
            type: integer
            minimum: 0
            default: 0
          items:
            items:
              $ref: '#/definitions/EsOrderItemStatus'
            type: array
          retailPrice:
            type: integer
            minimum: 0
            default: 0
          salePrice:
            type: integer
            minimum: 0
            default: 0
          subtotal:
            default: 0
            minimum: 0
            type: integer
          dueUpfront:
            default: 0
            minimum: 0
            type: integer
          platformFee:
            default: 0
            minimum: 0
            type: integer
          payInInstallments:
            type: boolean
          installmentPlan:
            $ref: '#/definitions/EsInstallmentPlan'
          totalPaymentsMade:
            minimum: 0
            type: integer
          totalNumberOfPayments:
            minimum: 0
            type: integer
          paid:
            type: boolean
            default: false
          orderId:
            type: string
          user:
            $ref: '#/definitions/EsOrderUser'
          surveys:
            type: object
            additionalProperties:
              $ref: '#/definitions/EsCheckoutSurvey'
          storeCurrency:
            type: string
          presentmentCurrency:
            type: string
          exchangeRate:
            type: number
            default: 1.0
          exchangeId:
            type: string
          customerId:
            type: string
          transactionIds:
            type: array
            items:
              type: string
          subscriptionId:
            type: string
          chargeTotal:
            default: 0
            minimum: 0
            type: integer
          chargedInPresentmentCurrency:
            default: 0
            minimum: 0
            type: integer
          refundTotal:
            default: 0
            minimum: 0
            type: integer
          refundInPresentmentCurrency:
            default: 0
            minimum: 0
            type: integer
          platformFeeTotal:
            default: 0
            minimum: 0
            type: integer
          paymentProcessorFeeTotal:
            default: 0
            minimum: 0
            type: integer
          feeTotal:
            default: 0
            minimum: 0
            type: integer
          isRefundPending:
            type: boolean
          pendingRefundId:
            type: string
          refunds:
            type: array
            items:
              $ref: '#/definitions/EsRefund'
          exchangeRates:
            type: object
            additionalProperties:
              $ref: '#/definitions/EsExchangeRate'
          claimCode:
            type: string
  EsRefundRequest:
    properties:
      message:
        type: string
      quantity:
        type: integer
    required:
      - quantity
      - reason
    type: object
  
  EsRefund:
    type: object
    allOf:
      - $ref: '#/definitions/EsRefundRequest'
      - properties:
          requestedWhen:
            type: integer
          processedWhen:
            type: integer
          isProcessed:
            type: boolean
          processedById:
            type: string
          quantity:
            type: integer
          message:
            type: integer
          merchantNotes:
            type: string
          amountRefunded:
            type: integer
            
  EsOrderItemPromotion:
    type: object
    properties:
      discountType: 
        type: string
      memberId:
        type: string
      membershipId:
        type: string
      membershipName:
        type: string
      referralCode:
        type: string
      appliedWhen:
        type: integer
      discountByAmount:
        type: integer
        minimum: 0
      discountByPercentage:
        type: number
        minimum: 0
        maximum: 0

  EsOrderItemStatus:
    properties:
      id:
        type: string
      surveyResponses:
        type: object
        additionalProperties:
          type: string
    type: object

  EsOrderUser:
    properties:
      email:
        type: string
      name:
        type: string
      phone:
        type: string
    type: object
    
  EsDSPagination:
    type: object
    properties:
      pageSize:
        type: integer
        format: int32
      nextCursor:
        type: string
  
  EsExchangeRate:
    type: number
    format: float
  
  EsCheckoutSurveyInput:
    type: object
    properties:
      service:
        type: string
      surveyId:
        type: string
  
  EsCheckoutSurvey:
    type: object
    allOf:
      - $ref: '#/definitions/EsCheckoutSurveyInput'
      - properties:
          completedWhen:
            type: integer
            minimum: 0
          isCompleted:
            type: boolean
  
  EsSuccess:
    properties:
      message:
        type: object
      success:
        type: boolean
    type: object
  
securityDefinitions:
  ServiceKey:
    in: header
    name: X-Service-Key
    description: Client Key
    type: apiKey
security:
  - ServiceKey: []
tags:
  - description: Manage Order items
    name: esOrderItems

parameters:
  
  orderItemId:
    description: Order Item Id
    in: path
    name: orderItemId
    required: true
    type: string

