swagger: '2.0'
info:
  contact:
    email: dev@edropin.com
    name: Saj Arora
  description: Store Internal service for eDropin
  license:
    name: UNLICENSED
  title: eDropin Store Internal
  version: 1.0.0
host: localhost:9004
basePath: /
schemes:
  - http
paths:

  ### CRON JOBS
  '/cron/delete':
    get:
      security: 
        - CronKey: []
      produces:
        - application/json
      responses:
        '200':
          description: Cron Job Run Result
          schema:
            $ref: '#/definitions/EsSuccess'
      tags:
        - esCron
      operationId: executeDeletionCron
      summary: Delete all store resources marked with isDeleted flag and take all necessary actions to clean up related resources
  '/cron/update-exchange-rate':
    get:
      security: 
        - CronKey: []
      produces:
        - application/json
      responses:
        '200':
          description: Cron Job Run Result
          schema:
            $ref: '#/definitions/EsSuccess'
      tags:
        - esCron
      operationId: updateExchangeRate
      summary: Update the store exchange rate
  
  
  ### PUBSUB
  '/pubsub/order-item-status':
    post:
      security:
        - PubsubKey: []
      produces:
        - application/json
      parameters:
        - description: Pubsub data
          in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/EsPubsubInput'
      responses:
        '200':
          description: Pubsub result
          schema:
            $ref: '#/definitions/EsSuccess'
      tags:
        - esPubsub
      operationId: updateOrderItemStatus
      summary: Update an order item status
  
  ### TASKS
  '/tasks/checkout-order':
    post:
      security:
        - TaskKey: []
      produces:
        - application/json
      parameters:
        - description: Order data
          in: body
          name: body
          required: true
          schema:
            type: object
      responses:
        '200':
          description: Task result
          schema:
            $ref: '#/definitions/EsSuccess'
      tags:
        - esTasks
      operationId: processMessage
      summary: Process a message
  
  '/webhooks/stripe-subscription':
    post:
      security: []
      produces:
        - application/json
      parameters:
        - description: Order data
          in: body
          name: body
          required: true
          schema:
            type: object
      responses:
        '200':
          description: Task result
          schema:
            $ref: '#/definitions/EsSuccess'
      tags:
        - esWebhooks
      operationId: processSubscription
      summary: Process a message
  
  ### OPS
  '/ops/migration/{buildId}':
    post:
      security:
        - AdminKey: []
      produces:
        - application/json
      parameters:
        - in: path
          required: true
          type: string
          name: buildId
          description: Build ID - Used for selecting the right case for migration
        - description: Op data
          in: body
          name: body
          required: false
          schema:
            type: object
      responses:
        '200':
          description: Pubsub result
          schema:
            $ref: '#/definitions/EsSuccess'
      tags:
        - esOps
      operationId: migrate
      summary: Migration endpoint
  
definitions:
  EsSuccess:
    properties:
      message:
        type: object
      success:
        type: boolean
    type: object
    
  EsPubsubInput:
    type: object
    properties:
      subscription:
        type: string
      data:
        type: string
      messageId:
        type: string
  
securityDefinitions:
  TaskKey:
    in: query
    name: apiKey
    description: Task Key
    type: apiKey
  PubsubKey:
    in: query
    name: apiKey
    description: Pubsub Key
    type: apiKey
  CronKey:
    in: query
    name: apiKey
    description: Cron Key
    type: apiKey
  AdminKey:
    in: header
    name: X-Admin-Key
    description: Admin Key
    type: apiKey
tags:
  - description: Handle all subscription callbacks
    name: esPubsub
  - description: Handle all cron jobs
    name: esCron
  - description: Handle all task callbacks
    name: esTasks
  - description: Handle all webhook callbacks
    name: esWebhooks
  - description: Handle all ops (system admin only)
    name: esOps

